name: mofleet

packages:
  - apps/**
  - packages/**

scripts:
  # melos bootstrap
  setup:
    exec: melos pub:get && melos dart:fix
  pub:get:
    exec: flutter pub get
  dart:fix:
    exec: dart fix --apply
  
  run:
    exec: flutter run --flavor development --target lib/main_development.dart
  analyze:
    exec: dart analyze .